[package]
name = "fourth-lesson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name="question2"
path = "./src/question2.rs"

[[bin]]
name = "question1"
path = "./src/question1.rs"

[dependencies]
